[package]
name = "curl-alternative"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
futures-util = "0.3.31"
tokio = { version = "1.44.2", features = ["full"] }
tokio-tungstenite = "0.26.2"
